# Generated by Django 2.2 on 2019-05-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.TNod'),
        ),
    ]
