# Generated by Django 2.2 on 2019-05-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190501_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Warehouse', verbose_name='Основной склад'),
        ),
    ]
