# Generated by Django 2.2 on 2019-04-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_container_cont_type'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('cont_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ContainerParams')),
            ],
        ),
        migrations.AlterField(
            model_name='containerproducts',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Container'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Container'),
        ),
    ]
