# Generated by Django 2.2 on 2019-04-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20190415_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentout',
            name='storage_ptr',
        ),
        migrations.RemoveField(
            model_name='documenttest',
            name='storage_ptr',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='DocumentIn',
        ),
        migrations.DeleteModel(
            name='DocumentOut',
        ),
        migrations.DeleteModel(
            name='DocumentTest',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
