# Generated by Django 2.2 on 2019-04-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse', '0006_rack_warehousecell'),
        ('storage', '0004_auto_20190415_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseCell')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_storage.storage_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DocumentPlanIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plan', models.IntegerField()),
                ('fact', models.IntegerField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseCell')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentIn',
            fields=[
                ('storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.Storage')),
                ('quantity', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('doc_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.DocumentPlanIn')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('storage.storage',),
        ),
    ]
