# Generated by Django 2.2 on 2019-04-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingModelProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('use_date', models.BooleanField(default=False)),
                ('use_serial', models.BooleanField(default=False)),
                ('use_parts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.AccountingModelProducts')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnitsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField(default=1)),
                ('unit_width', models.DecimalField(decimal_places=3, max_digits=5, max_length=10)),
                ('unit_height', models.DecimalField(decimal_places=3, max_digits=5, max_length=10)),
                ('unit_length', models.DecimalField(decimal_places=3, max_digits=5, max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.StorageUnitsClass')),
            ],
        ),
    ]
