# Generated by Django 2.2 on 2019-04-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='cont_type',
        ),
    ]
