# Generated by Django 2.2 on 2019-04-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190428_0852'),
        ('product', '0002_remove_container_cont_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Container',
        ),
    ]
