# Generated by Django 2.2 on 2019-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
