# Generated by Django 2.2 on 2019-05-04 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190504_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_unit', to='product.StorageUnit'),
        ),
    ]
