# Generated by Django 2.2 on 2019-05-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190504_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, max_length=10, null=True, verbose_name='Цена'),
        ),
    ]
