# Generated by Django 2.2 on 2019-05-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190504_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingmodelproducts',
            name='use_mono_container',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='product.AccountingModelProducts', verbose_name='Модель учета'),
        ),
    ]
