# Generated by Django 2.2 on 2019-04-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('product', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseCell', verbose_name='Адрес приемки')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(verbose_name='Плановое количество базовых едениц')),
                ('fact', models.IntegerField(verbose_name='Фактическое количество базовых едениц')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incoming.DocumentPlan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Товар')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.StorageUnit', verbose_name='Единица хранения')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.Storage')),
                ('quantity', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ContainerParams')),
                ('doc_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incoming.DocumentPlan')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.StorageUnit')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('storage.storage',),
        ),
    ]
