# Generated by Django 2.2 on 2019-04-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_auto_20190428_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproducts',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='incoming.DocumentPlan'),
        ),
    ]
