# Generated by Django 2.2 on 2019-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0008_auto_20190501_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentplan',
            name='bill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentplan',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
