# Generated by Django 2.2 on 2019-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0009_auto_20190502_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentplan',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
