# Generated by Django 2.2 on 2019-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0010_documentplan_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentplan',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
