# Generated by Django 2.2 on 2019-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0011_auto_20190502_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproducts',
            name='fact',
            field=models.IntegerField(default=0, verbose_name='Фактическое количество базовых едениц'),
        ),
    ]
