# Generated by Django 2.2 on 2019-05-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0013_auto_20190504_0323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentproducts',
            unique_together=set(),
        ),
    ]
