# Generated by Django 2.2 on 2019-05-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20190501_0245'),
        ('incoming', '0016_documententry_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententry',
            name='in_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Container'),
        ),
    ]
