# Generated by Django 2.2 on 2019-04-17 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=2, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Стеллаж',
                'verbose_name_plural': 'Стеллажи',
            },
        ),
        migrations.CreateModel(
            name='WarehouseCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.CharField(max_length=2, verbose_name='Ярус')),
                ('position', models.CharField(max_length=2, verbose_name='Позиция')),
                ('cell_width', models.DecimalField(decimal_places=3, max_digits=5, max_length=10, verbose_name='Ширина')),
                ('cell_height', models.DecimalField(decimal_places=3, max_digits=5, max_length=10, verbose_name='Высота')),
                ('cell_length', models.DecimalField(decimal_places=3, max_digits=5, max_length=10, verbose_name='Глубина')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Rack', verbose_name='Стеллаж')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'ЯСклады',
            },
        ),
    ]
