# Generated by Django 2.2 on 2019-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('blocked', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
