# Generated by Django 2.2 on 2019-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecell',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Штрих код'),
        ),
    ]
