# Generated by Django 2.2 on 2019-04-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190413_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.CharField(max_length=2)),
                ('position', models.CharField(max_length=2)),
                ('cell_width', models.DecimalField(decimal_places=3, max_digits=5, max_length=10)),
                ('cell_height', models.DecimalField(decimal_places=3, max_digits=5, max_length=10)),
                ('cell_length', models.DecimalField(decimal_places=3, max_digits=5, max_length=10)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Rack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
