# Generated by Django 2.2 on 2019-05-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20190501_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='owner',
        ),
    ]
