# Generated by Django 2.2 on 2019-05-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_remove_warehouse_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
