# Generated by Django 2.2 on 2019-05-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_warehousecell_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehousecell',
            unique_together={('rack', 'tier', 'position', 'name')},
        ),
    ]
