# Generated by Django 2.2 on 2019-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20190505_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecell',
            name='cell_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Storage'), (2, 'Acceptance'), (3, 'Shipment')], default=1, null=True),
        ),
    ]
