# Generated by Django 2.2 on 2019-05-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190501_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
